server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/petrealm
  application:
    name: shopservice
  webflux:
    base-path: ${SERVER_SERVLET_CONTEXT_PATH:/api/v1/shop}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
    health:
      sensitive: false
