server:
  port: 0

spring:
  application:
    name: shopservice
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
    health:
      sensitive: false
